### ISSUE TITLE
Does http://y.yakamo.org:3000/current no longer work?

### ISSUE THREAD

**Issue by xaozai** [yakamok/yggdrasil-stats#8]
Do you plan to restore the functionality of this service?

Is there an up-to- date list of all Yggdrasil nodes available somewhere?

**Comment by yakamok** [comment]
Hi Sorry for the incredibly late response. No that service is no longer functioning. I doubt i will bring it back at the moment as i just dont have enough time to work on projects right now. If you look on the website there are links to the matrix group and IRC group where they will have the info you need about nodes and services.
